### ISSUE TITLE
How do I view another user's profile?

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#11]
This was not addressed in the specs

**Comment by smummolo** [comment]
should be able to tap their icon or name to go to their profile

**Comment by CodySwannGT** [comment]
Is this universal? Everywhere you see someone's name, clicking it should take you to their profile?

I ask cause that might get dicey on the alerts screen and the profile screen where we have tap events on the cells themselves kinda thing. 

Totally possible programmatically but didn't know if you want that fine level of tapping.

**Comment by smummolo** [comment]
yes universal for the name, the only exception for the icon would be the choosing sides functionality.

**Comment by CodySwannGT** [comment]
@adamespn any questions here?

**Comment by adamespn** [comment]
Yes. Please see #47 - there appears to be a disconnect between these two tickets

**Comment by adamespn** [comment]
@smummolo In #47 we have a statement that there will be no profile screens, but in here we are saying there are profile screens. Can you clarify which one is right and provide a design if we are adding profile screens for other users?

**Comment by jiakeliu** [comment]
Clicking on a user portrait should go to their profile screen. Here's the wire-frame and I'm asking Randy to provide a mockup:

![profile](https://cloud.githubusercontent.com/assets/1039583/7002130/7ceed552-dbfa-11e4-86c8-e7a257914782.png)

**Comment by jiakeliu** [comment]
![profile](https://cloud.githubusercontent.com/assets/1039583/7016595/5816fc1c-dc9c-11e4-9415-742384a6efd8.jpg)

**Comment by adamespn** [comment]
Quick question: Should my profile screen match this screen?

**Comment by jiakeliu** [comment]
The "Follow" button changes to "Edit" on my profile screen.

I will mock up the Profile Edit screen, but if you need a place holder for now, we just need text fields for Photo, Name, Username, Email, and Phone.

**Comment by jiakeliu** [comment]
Just checked out the build. Great to see the new profile screen taking shape! Couple of things:

Can we increase the size of the bet feed at the bottom of the Profile screen to take up the entire width of the screen? 

The entire screen, including the portrait and the selectors (WON, LOST, DRAWS, ACTIVE), should be scrollable to maximize the vertical view of the bet feed. The ideal UI behavior is the selectors would sticky to the top when a user scrolls down on this screen.

**Comment by adamespn** [comment]
OK - got it - that's going to take a little time - also, I wonder what happens when I scroll a long way down and I want to see the profile again

**Comment by jiakeliu** [comment]
I think the default iOS UX for scroll to the top of a long list is to tap at the top of the screen: http://stackoverflow.com/questions/8951357/scroll-uitableview-to-top-when-tapping-top-of-the-screen

Alternatively, tapping Profile again should go to the top of the screen too.

**Comment by adamespn** [comment]
Ok

**Comment by adamespn** [comment]
This last scrolling change could be a little tricky. I might punt this into next iteration or into future considerations

**Comment by husseinm** [comment]
This is fixed by the latest commit

**Comment by jiakeliu** [comment]
@husseinm please assign the ticket to me instead of closing it. So I can check it against the release.

**Comment by jiakeliu** [comment]
Wars are not showing up correctly in the Profile screen. Looks like it's showing my own wars instead of the Profile owner's wars.

**Comment by husseinm** [comment]
This should be corrected in the latest commit.

**Comment by jiakeliu** [comment]
Won/Lost wars are not displayed. Draws/Ongoing war counts are not correct. Please assign to Cody if backend issue.

**Comment by husseinm** [comment]
Should now be 100% - please check TF

**Comment by jiakeliu** [comment]
War list doesn't update when I switch between "Draws" and "Ongoing". Won/Lost still show 0 count.

**Comment by husseinm** [comment]
The Won/Lost counts are zero for you because that is what it correctly is. Check Cody's profile.

I am looking at your profile right now and it does change the war list from 7 to the 1 drawn war that you have. Not sure what is going on for your end, did you update at TF?

**Comment by jiakeliu** [comment]
I tried reinstalling the app and now I'm stuck at the Thumbwar background image loading screen

**Comment by husseinm** [comment]
Try to restart your phone with both home + power buttons?

On 6/16/2015 5:05 PM, Jiake Liu wrote:
>
> I tried reinstalling the app and now I'm stuck at the Thumbwar 
> background image loading screen
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112569775>.
>

-- 
Mahdi Hussein
m@hdihusse.in <mailto:m@hdihusse.in> | mahdihusse.in

**Comment by jiakeliu** [comment]
You know what's wierd? The "Login with Facebook" button is not showing up on the Thumbwar background image page, but when I tap that area where the button is supposed to be, Facebook actually loads up.

**Comment by jiakeliu** [comment]
Can you try reinstalling the app on your phone and see if you can reproduce that bug?

**Comment by jiakeliu** [comment]
For my wars, why is the bet I have with Alex showing up in both Draws and Ongoing?

**Comment by CodySwannGT** [comment]
I'll chime in here.

My guess is it's because we didn't clearly define what these different
statuses are or represent.

For example. We have this "propose an outcome" where the challenger can say
"I won" and the opponent can say "I won".

What happens when the opponent says "I won" and the challenger hasn't
responded yet?

Is that "loss" is that "in_progess"?

What about a thumbwar that is sent to someone and that someone ignores it?
Is that in_progress? According to the data model, it is in_progress. Or is
that some other state that we haven't added into the data model that were
going to have to toss in there and hope it doesn't break other
functionality?

There are a lot of scenarios like that that we kind of just glossed over in
another push to get new features in there.

My guess is that the server is going to have a lot of inconsistencies now
because we kind of glibly added that type of stuff.



On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com> wrote:

> For my wars, why is the bet I have with Alex showing up in both Draws and
> Ongoing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112571432>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by husseinm** [comment]
So Cody was spot on there for the issue with the war showing up in two 
different places. At this point anything with the profile screen is most 
likely the server just returning data that does not reflect the changes 
we keep making. Unless it is a blatant UI issue and not data related in 
any way, like the activity spinners - then it is simply the API not 
keeping up with us, just as Cody said.

Regarding the Facebook button, I will work to finish the bet closing as 
that is what you told me was the highest priority this week was. If I 
finish earlier I will work on the login screen, I have never even looked 
at that screen's code since we have been working so much on the 
post-login UI.

**Comment by jiakeliu** [comment]
In your example, when the opponent says "I Won" and the challenger hasn't responded yet, the war is "in_progress". Essentially until both participants agree to an outcome, the war is always "in_progress".

In the second example, an ignored war should be in a "pending" status that should not show up in the public feed. This maybe a new state that we need to add.

Here are the war status from the UX perspective:

1. Pending - a war that's created but has not been accepted or declined by the opponent
2. Ongoing (in_progress) - a war that's been accepted and has no winner declared
3. Won - a war that the user won (both sides agree)
4. Lost - a war that the user lost (both sides agree)
5. Draw - a push (both sides agree)

**Comment by jiakeliu** [comment]
@husseinm Sounds good. I'll create a separate bug ticket for the login screen. I think it's a new bug since the button showed up fine in previous versions.

**Comment by CodySwannGT** [comment]
And a thumbwar where the two users disagree? That will count as a push
today however, the API is querying challenges not thumbwars.

This is the problem we're going to run into.

Remember. The data model IS NOT

Thumbwar has a challenger and has an opponent.

The data model is:

Thumbwar has a challenger and has many opponents.

We're just constricting it at the UI level to have one opponent.

So I can't query "thumbwars where status == won and opponent_id == x"

I have to do a join to get the data which is going to degrade quickly.

So I was querying challenges

"Challenges where status == won and opponent_id = x"

But that doesn't take into account the condition where users don't agree or
haven't responded.

So the "quick" solution I tried to throw together wasn't sufficient.

So now I have to change the data model which, again, I don't know when I'll
have time to do that and I also don't know what new bugs that will
introduce.

All that is just saying that July 1, unfortunately, probably just went out
the window. :/

On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com> wrote:

> In your example, when the opponent says "I Won" and the challenger hasn't
> responded yet, the war is "in_progress". Essentially until both
> participants agree to an outcome, the war is always "in_progress".
>
> In the second example, an ignored war should be in a "pending" status that
> should not show up in the public feed. This maybe a new state that we need
> to add.
>
> Here are the war status from the UX perspective:
>
>    1. Pending - a war that's created but has not been accepted or
>    declined by the opponent
>    2. Ongoing (in_progress) - a war that's been accepted and has no
>    winner declared
>    3. Won - a war that the user won (both sides agree)
>    4. Lost - a war that the user lost (both sides agree)
>    5. Draw - a push (both sides agree)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112585962>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by jiakeliu** [comment]
A thumbwar that both users disagree will always be "in_progress" until they
come to an agreement thorugh the back and forth winner declaration with
comment/picture process.  Some wars just require one declaration and the
opponent to accept to close, some may need 10 back and forths, and some may
never close because both sides can't come to an agreement.


On Tuesday, June 16, 2015, Cody Swann <notifications@github.com> wrote:

> And a thumbwar where the two users disagree? That will count as a push
> today however, the API is querying challenges not thumbwars.
>
> This is the problem we're going to run into.
>
> Remember. The data model IS NOT
>
> Thumbwar has a challenger and has an opponent.
>
> The data model is:
>
> Thumbwar has a challenger and has many opponents.
>
> We're just constricting it at the UI level to have one opponent.
>
> So I can't query "thumbwars where status == won and opponent_id == x"
>
> I have to do a join to get the data which is going to degrade quickly.
>
> So I was querying challenges
>
> "Challenges where status == won and opponent_id = x"
>
> But that doesn't take into account the condition where users don't agree or
> haven't responded.
>
> So the "quick" solution I tried to throw together wasn't sufficient.
>
> So now I have to change the data model which, again, I don't know when I'll
> have time to do that and I also don't know what new bugs that will
> introduce.
>
> All that is just saying that July 1, unfortunately, probably just went out
> the window. :/
>
> On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > In your example, when the opponent says "I Won" and the challenger hasn't
> > responded yet, the war is "in_progress". Essentially until both
> > participants agree to an outcome, the war is always "in_progress".
> >
> > In the second example, an ignored war should be in a "pending" status
> that
> > should not show up in the public feed. This maybe a new state that we
> need
> > to add.
> >
> > Here are the war status from the UX perspective:
> >
> > 1. Pending - a war that's created but has not been accepted or
> > declined by the opponent
> > 2. Ongoing (in_progress) - a war that's been accepted and has no
> > winner declared
> > 3. Won - a war that the user won (both sides agree)
> > 4. Lost - a war that the user lost (both sides agree)
> > 5. Draw - a push (both sides agree)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112585962
> >
> > .
> >
>
>
> --
> Cody Swann - CEO, Gunner Technology
> T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | www.gunnertech.com
> <http://www.gunnertech.com/>Skype: cody.swann
>
> *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> files and/or email messages attached to it, is intended for the sole use of
> the individual or entity to whom it is addressed, and may contain
> information that is legally privileged, confidential and restricted from
> disclosure. If you are not the intended recipient, or responsible for
> delivery to that person, you are hereby notified that any dissemination or
> copying of this communication is STRICTLY PROHIBITED. In such case please
> notify the sender by reply email and delete this message without reading,
> printing or saving.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112595148>
> .
>


-- 
Sent from Gmail Mobile

**Comment by jiakeliu** [comment]
Out of curiosity, what was the decision process behind the one challenger
to many opponents model? Is it for the use case that someone can issue a
challenge and people can take on that challenge at will?

On Tuesday, June 16, 2015, Cody Swann <notifications@github.com> wrote:

> And a thumbwar where the two users disagree? That will count as a push
> today however, the API is querying challenges not thumbwars.
>
> This is the problem we're going to run into.
>
> Remember. The data model IS NOT
>
> Thumbwar has a challenger and has an opponent.
>
> The data model is:
>
> Thumbwar has a challenger and has many opponents.
>
> We're just constricting it at the UI level to have one opponent.
>
> So I can't query "thumbwars where status == won and opponent_id == x"
>
> I have to do a join to get the data which is going to degrade quickly.
>
> So I was querying challenges
>
> "Challenges where status == won and opponent_id = x"
>
> But that doesn't take into account the condition where users don't agree or
> haven't responded.
>
> So the "quick" solution I tried to throw together wasn't sufficient.
>
> So now I have to change the data model which, again, I don't know when I'll
> have time to do that and I also don't know what new bugs that will
> introduce.
>
> All that is just saying that July 1, unfortunately, probably just went out
> the window. :/
>
> On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > In your example, when the opponent says "I Won" and the challenger hasn't
> > responded yet, the war is "in_progress". Essentially until both
> > participants agree to an outcome, the war is always "in_progress".
> >
> > In the second example, an ignored war should be in a "pending" status
> that
> > should not show up in the public feed. This maybe a new state that we
> need
> > to add.
> >
> > Here are the war status from the UX perspective:
> >
> > 1. Pending - a war that's created but has not been accepted or
> > declined by the opponent
> > 2. Ongoing (in_progress) - a war that's been accepted and has no
> > winner declared
> > 3. Won - a war that the user won (both sides agree)
> > 4. Lost - a war that the user lost (both sides agree)
> > 5. Draw - a push (both sides agree)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112585962
> >
> > .
> >
>
>
> --
> Cody Swann - CEO, Gunner Technology
> T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | www.gunnertech.com
> <http://www.gunnertech.com/>Skype: cody.swann
>
> *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> files and/or email messages attached to it, is intended for the sole use of
> the individual or entity to whom it is addressed, and may contain
> information that is legally privileged, confidential and restricted from
> disclosure. If you are not the intended recipient, or responsible for
> delivery to that person, you are hereby notified that any dissemination or
> copying of this communication is STRICTLY PROHIBITED. In such case please
> notify the sender by reply email and delete this message without reading,
> printing or saving.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112595148>
> .
>


-- 
Sent from Gmail Mobile

**Comment by husseinm** [comment]
No, it is because he wanted to leave the ability to have multiple 
opponents. Remember I believe it was Alex who wanted to have that as a 
crucial feature for the MVP?

On 6/16/2015 7:30 PM, Jiake Liu wrote:
> Out of curiosity, what was the decision process behind the one challenger
> to many opponents model? Is it for the use case that someone can issue a
> challenge and people can take on that challenge at will?
>
> On Tuesday, June 16, 2015, Cody Swann <notifications@github.com> wrote:
>
> > And a thumbwar where the two users disagree? That will count as a push
> > today however, the API is querying challenges not thumbwars.
> >
> > This is the problem we're going to run into.
> >
> > Remember. The data model IS NOT
> >
> > Thumbwar has a challenger and has an opponent.
> >
> > The data model is:
> >
> > Thumbwar has a challenger and has many opponents.
> >
> > We're just constricting it at the UI level to have one opponent.
> >
> > So I can't query "thumbwars where status == won and opponent_id == x"
> >
> > I have to do a join to get the data which is going to degrade quickly.
> >
> > So I was querying challenges
> >
> > "Challenges where status == won and opponent_id = x"
> >
> > But that doesn't take into account the condition where users don't 
> agree or
> > haven't responded.
> >
> > So the "quick" solution I tried to throw together wasn't sufficient.
> >
> > So now I have to change the data model which, again, I don't know 
> when I'll
> > have time to do that and I also don't know what new bugs that will
> > introduce.
> >
> > All that is just saying that July 1, unfortunately, probably just 
> went out
> > the window. :/
> >
> > On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > In your example, when the opponent says "I Won" and the challenger 
> hasn't
> > > responded yet, the war is "in_progress". Essentially until both
> > > participants agree to an outcome, the war is always "in_progress".
> > >
> > > In the second example, an ignored war should be in a "pending" status
> > that
> > > should not show up in the public feed. This maybe a new state that we
> > need
> > > to add.
> > >
> > > Here are the war status from the UX perspective:
> > >
> > > 1. Pending - a war that's created but has not been accepted or
> > > declined by the opponent
> > > 2. Ongoing (in_progress) - a war that's been accepted and has no
> > > winner declared
> > > 3. Won - a war that the user won (both sides agree)
> > > 4. Lost - a war that the user lost (both sides agree)
> > > 5. Draw - a push (both sides agree)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112585962
> > >
> > > .
> > >
> >
> >
> > --
> > Cody Swann - CEO, Gunner Technology
> > T: 213.915.4083 | cody@gunnertech.com
> > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | 
> www.gunnertech.com
> > <http://www.gunnertech.com/>Skype: cody.swann
> >
> > *CONFIDENTIALITY NOTICE: This email message, together with any 
> documents,
> > files and/or email messages attached to it, is intended for the sole 
> use of
> > the individual or entity to whom it is addressed, and may contain
> > information that is legally privileged, confidential and restricted from
> > disclosure. If you are not the intended recipient, or responsible for
> > delivery to that person, you are hereby notified that any 
> dissemination or
> > copying of this communication is STRICTLY PROHIBITED. In such case 
> please
> > notify the sender by reply email and delete this message without 
> reading,
> > printing or saving.*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112595148>
> > .
> >
>
>
> -- 
> Sent from Gmail Mobile
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112601948>.
>

-- 
Mahdi Hussein
m@hdihusse.in <mailto:m@hdihusse.in> | mahdihusse.in

**Comment by CodySwannGT** [comment]
Bob actually. But yeah. Multiple opponents at one point was an absolute
must for the MVP.

On Tuesday, June 16, 2015, Mahdi Hussein <notifications@github.com> wrote:

> No, it is because he wanted to leave the ability to have multiple
> opponents. Remember I believe it was Alex who wanted to have that as a
> crucial feature for the MVP?
>
> On 6/16/2015 7:30 PM, Jiake Liu wrote:
> > Out of curiosity, what was the decision process behind the one challenger
> > to many opponents model? Is it for the use case that someone can issue a
> > challenge and people can take on that challenge at will?
> >
> > On Tuesday, June 16, 2015, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > And a thumbwar where the two users disagree? That will count as a push
> > > today however, the API is querying challenges not thumbwars.
> > >
> > > This is the problem we're going to run into.
> > >
> > > Remember. The data model IS NOT
> > >
> > > Thumbwar has a challenger and has an opponent.
> > >
> > > The data model is:
> > >
> > > Thumbwar has a challenger and has many opponents.
> > >
> > > We're just constricting it at the UI level to have one opponent.
> > >
> > > So I can't query "thumbwars where status == won and opponent_id == x"
> > >
> > > I have to do a join to get the data which is going to degrade quickly.
> > >
> > > So I was querying challenges
> > >
> > > "Challenges where status == won and opponent_id = x"
> > >
> > > But that doesn't take into account the condition where users don't
> > agree or
> > > haven't responded.
> > >
> > > So the "quick" solution I tried to throw together wasn't sufficient.
> > >
> > > So now I have to change the data model which, again, I don't know
> > when I'll
> > > have time to do that and I also don't know what new bugs that will
> > > introduce.
> > >
> > > All that is just saying that July 1, unfortunately, probably just
> > went out
> > > the window. :/
> > >
> > > On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > > > In your example, when the opponent says "I Won" and the challenger
> > hasn't
> > > > responded yet, the war is "in_progress". Essentially until both
> > > > participants agree to an outcome, the war is always "in_progress".
> > > >
> > > > In the second example, an ignored war should be in a "pending" status
> > > that
> > > > should not show up in the public feed. This maybe a new state that we
> > > need
> > > > to add.
> > > >
> > > > Here are the war status from the UX perspective:
> > > >
> > > > 1. Pending - a war that's created but has not been accepted or
> > > > declined by the opponent
> > > > 2. Ongoing (in_progress) - a war that's been accepted and has no
> > > > winner declared
> > > > 3. Won - a war that the user won (both sides agree)
> > > > 4. Lost - a war that the user lost (both sides agree)
> > > > 5. Draw - a push (both sides agree)
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112585962
> > > >
> > > > .
> > > >
> > >
> > >
> > > --
> > > Cody Swann - CEO, Gunner Technology
> > > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>
> > > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>');> |
> > www.gunnertech.com
> > > <http://www.gunnertech.com/>Skype: cody.swann
> > >
> > > *CONFIDENTIALITY NOTICE: This email message, together with any
> > documents,
> > > files and/or email messages attached to it, is intended for the sole
> > use of
> > > the individual or entity to whom it is addressed, and may contain
> > > information that is legally privileged, confidential and restricted
> from
> > > disclosure. If you are not the intended recipient, or responsible for
> > > delivery to that person, you are hereby notified that any
> > dissemination or
> > > copying of this communication is STRICTLY PROHIBITED. In such case
> > please
> > > notify the sender by reply email and delete this message without
> > reading,
> > > printing or saving.*
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112595148
> >
> > > .
> > >
> >
> >
> > --
> > Sent from Gmail Mobile
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112601948
> >.
> >
>
> --
> Mahdi Hussein
> m@hdihusse.in <javascript:_e(%7B%7D,'cvml','m@hdihusse.in');> <mailto:
> m@hdihusse.in <javascript:_e(%7B%7D,'cvml','m@hdihusse.in');>> |
> mahdihusse.in
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112602381>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by jiakeliu** [comment]
Gotcha. That can be accomplished by our siding feature right?

**Comment by CodySwannGT** [comment]
Yeah. Well. That's what happened.

Multiple opponents morphed into siding.

And actually, that was a hack, too. Because initially, we wanted the
ability to "follow" a war.

So we hacked the data model for following to have a "side" field.

On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com> wrote:

> Gotcha. That can be accomplished by our siding feature right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112602612>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by husseinm** [comment]
I believe we still need the ability to "follow" a war, that is one of 
the features for the ellipses Jiake is having me do. I haven't checked 
whether the API supports it yet.

On 6/16/2015 7:35 PM, Cody Swann wrote:
> Yeah. Well. That's what happened.
>
> Multiple opponents morphed into siding.
>
> And actually, that was a hack, too. Because initially, we wanted the
> ability to "follow" a war.
>
> So we hacked the data model for following to have a "side" field.
>
> On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com> wrote:
>
> > Gotcha. That can be accomplished by our siding feature right?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112602612>
> > .
> >
>
>
> -- 
> Cody Swann - CEO, Gunner Technology
> T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
> <http://www.gunnertech.com/>Skype: cody.swann
>
> *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> files and/or email messages attached to it, is intended for the sole 
> use of
> the individual or entity to whom it is addressed, and may contain
> information that is legally privileged, confidential and restricted from
> disclosure. If you are not the intended recipient, or responsible for
> delivery to that person, you are hereby notified that any dissemination or
> copying of this communication is STRICTLY PROHIBITED. In such case please
> notify the sender by reply email and delete this message without reading,
> printing or saving.*
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112602787>.
>

-- 
Mahdi Hussein
m@hdihusse.in <mailto:m@hdihusse.in> | mahdihusse.in

**Comment by jiakeliu** [comment]
Okay.

Anyway, if we remove the "Draw" tab in Profile view, can that be the short term solution without modifying the data model? So we essentially show Won, Lost, and Ongoing.

**Comment by jiakeliu** [comment]
@husseinm "Follow war" feature should just be a placeholder button for now in the ellipses drop down menu.

**Comment by husseinm** [comment]
Not a problem on my side. Jiake, do you want that as a solution?

On 6/16/2015 7:38 PM, Jiake Liu wrote:
>
> Okay.
>
> Anyway, if we remove the "Draw" tab in Profile view, can that be the 
> short term solution without modifying the data model? So we 
> essentially show Won, Lost, and Ongoing.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112603173>.
>

-- 
Mahdi Hussein
m@hdihusse.in <mailto:m@hdihusse.in> | mahdihusse.in

**Comment by jiakeliu** [comment]
How are we currently distinguishing "push" and "in_progress"?

**Comment by CodySwannGT** [comment]
In response to Mahdi:

SMH. Following IS siding. We agreed that in order to follow, you had to
choose a side to force participation.

If we're changing that now, too, we really are a long ways away from MVP.

In response to Jiake:

My comments were more about regression testing.

It's entirely possible, I get an hour and just nail it and nothing breaks
or anything like that.

It's also possible that we have to play with it for a long time, tweaking
it as we go like we had to do initially.

So, let's just go forward with the change and I'll try to come up with a
clever solution that doesn't require a major overhaul to the data model.

On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com> wrote:

> Okay.
>
> Anyway, if we remove the "Draw" tab in Profile view, can that be the short
> term solution without modifying the data model? So we essentially show Won,
> Lost, and Ongoing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112603173>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by jiakeliu** [comment]
@CodySwannGT Re: follow/siding, I like that, let's keep it. And sounds good about the plan to move forward.

@husseinm, please remove "Follow this Thumbwar" and just have "Report this Thumbwar" as a place holder item in the ellipses drop-down.

**Comment by CodySwannGT** [comment]
10-4. Will do.

On Tuesday, June 16, 2015, Jiake Liu <notifications@github.com> wrote:

> @CodySwannGT <https://github.com/CodySwannGT> Re: follow/siding, I like
> that, let's keep it. And sounds good about the plan to move forward.
>
> @husseinm <https://github.com/husseinm>, please remove "Follow this
> Thumbwar" and just have "Report this Thumbwar" as a place holder item in
> the ellipses drop-down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/11#issuecomment-112604421>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*
